CI: Set W3C status in spec-prod config file
In order for Echidna-based autopublishing to TR space to succeed, the
document status can’t be ED but instead must be WD or CR. So this change
sets it to WD in the spec-prod config file.

Otherwise, without this change, Echidna throws an exception:

https://labs.w3.org/echidna/api/status?id=9433f07f-8e57-4c89-a06e-9c9afd347da9

> Error: [EXCEPTION] The document could not be parsed, it's neither a TR
> document nor a Member Submission.